BN-1204-validations-only-for-minting-case-3_step_3
Topl/BramblSc pull request #116
Opened 2023-09-22 13:54 UTC by nandotorterolo

## Purpose

Implement **case3**, 

Validations only for minting (After projection to min (only if for all inputs and outputs isMint == true))
- asset minted correspond to token supply in series policy
- It is not being considered series outputs value, because they will be implemented on Transfer-Series-Funds validation

https://topl.atlassian.net/wiki/spaces/LABS/pages/678658061/Validation+TAMv2+Transactions+-+Meeting+Fernando+Edmundo+2023-09-08

## Testing
unit test and preparePR

## Tickets
https://topl.atlassian.net/browse/BN-1201

2023-09-25 17:08 UTC, DiademShoukralla commented on brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
> +            (s.quantity: BigInt) * (tokenSupplied: BigInt) % (a.quantity: BigInt) == 0
I'm not sure if this is correct. 

Consider the following case where `s.quantity = 2` and `tokenSupply = 3` and `a.quantity = 2`. The check would pass but I believe it should be invalid since `a.quantity` is not a multiple of `tokenSupply`. Thus failing the rule "asset minted correspond to token supply in series policy"

Perhaps we need to check if the quantity is a multiple of token supply separately from checking there is enough total supply. Maybe something like
```
tokenSupplied % a.quantity == 0 // Is minted quantity a multiple of token supply?
&&
s.quantity * tokenSupplied >= a.quantity  // Is there enough series supply to mint asset quantity?
```

What do you think?

2023-09-25 17:08 UTC, DiademShoukralla commented on brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseCSpec.scala
> + *  -  the number of series constructor tokens burned matches the number of assets minted (only applies for limited token supply)
Removing since this statement is not validated in these set of validations. This rule will be validated as part of Transfer-Series-Funds validation
```suggestion
```

2023-09-25 17:54 UTC, nandotorterolo commented on brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
> +            (s.quantity: BigInt) * (tokenSupplied: BigInt) % (a.quantity: BigInt) == 0
Thanks for reviewing it, good catch. I will update using your logic, (with a small change because a.quantity >= tokenSupplied). 

>   (a.quantity: BigInt) % (tokenSupplied: BigInt) == 0 

a new test was created with your input suggestion.

2023-09-26 19:57 UTC, mundacho requested changes

2023-09-27 12:24 UTC, nandotorterolo commented on brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
> +    val validAssets = assets.forall { a =>
let's chat about it, I think we covered the case for other assets, I will add a test to understand your point.
Would be great If I am wrong to create more unit tests on this case

2023-09-29 14:13 UTC, DiademShoukralla commented on brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
> +              burned * tokenSupplied == (ams.quantity: BigInt)
Per conversation this morning, `ams.quantity` should be replaced with a sum of all the Asset Minting Statements with the same seriesId

2023-10-02 21:37 UTC, DiademShoukralla approved these changes
LGTM!

2023-10-05 21:02 UTC, mundacho approved these changes
I think we are there, just double check that that validation is being made somewhere and we are there.

2023-10-05 21:02 UTC, mundacho commented on brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
> +              (ams.quantity: BigInt) <= s.quantity * tokenSupplied &&
are we checking somewhere else that: `ams.quantity % tokenSupplied == 0`? If yes, then nothing else to add

2023-10-05 21:45 UTC, merged