TSDK-460: Update how Credentialler retrieves information
Topl/BramblSc pull request #53
Opened 2023-04-28 18:23 UTC by DiademShoukralla

## Purpose

Previously the Credentialler was under the assumption that indices (x/y/z) were associated to a UTXO. We know now that this is not the case as indices are associated to a Key Pair which can map to one or more SignaturePropositions and a UTXO's lock may contain many SignaturePropositions.

## Approach

This PR contains changes to Credentialler, TransactionBuilder, and DataApi. At a high level, instead of the Credentialler retrieving the indices for a utxo, the Credentialler will retrieve the individual secrets needed for each proposition.

Specifically: 
- A SignatureProposition will map to Indices in the DataApi
- A DigestProposition will map to a Preimage in the DataApi

DataApi was updated to include functions to support this:
- Remvoed `getIndicesByTxoAddress`  since a UTXO/STXO is not directly associated with indices
- Changed return types to be F[Either[XX, YY]]] instead of Option[YY] to utilize the F context as well as to be consistent with  the return types of the other DataApi functions
- Added functions `getPreimage` and `getIndices` to support the functionality needed in Credentialler

Additionally, TransactionBuilder.constructUnprovenInput was modified as well to conform with the updated DataApi signatures.

## Testing

- Added a new test for TransactionBuilder to ensure failures are captured properly and updated a test for Credentialler. Lots of changes to MockHelpers and MockDataApi were needed
- Ran `checkPR` and ensure was successful

## Tickets
* Closes TSDK-460

2023-04-28 21:16 UTC, mundacho requested changes
I put some comments that we need to discuss before merging.

2023-04-28 21:16 UTC, mundacho commented on brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
> +  def getUtxoByTxoAddress(address: TransactionOutputAddress): F[Either[DataApiException, UnspentTransactionOutput]]
This might need to return a list of UTXOs

2023-04-28 21:16 UTC, mundacho commented on brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
> +  def getIndices(propositionEvidence: Evidence): F[Either[DataApiException, Indices]]
What happens when the proposition evidence has multiple signatures??

2023-04-28 22:32 UTC, DiademShoukralla commented on brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
> +  def getIndices(propositionEvidence: Evidence): F[Either[DataApiException, Indices]]
The `propositionEvidence` is meant to only be for a Signature proposition, in which case, only a single signature and indices are associated with it. I wasn't sure how to enforce that the evidence should only be for the specific type of proposition, so I will update the `getIndices` and `getPreimage` functions to instead take in `Proposition.DigitalSignature` and `Proof.DigitalSignature` respectivefully.

2023-04-28 22:34 UTC, DiademShoukralla commented on brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderInterpreter.scala
> +          utxo <- EitherT(dataApi.getUtxoByTxoAddress(data.address))
You are correct for LockAddresses that there may be multiple UTXOs, but for a TransactionOutputAddress I believe there should be only one UTXO since this type of address refers to a Transaction Output directly. 

However,  I think this function should be modified to take in either a TransactionOutputAddress or a LockAddress. I was hoping to do that change as a part of a separate ticket (perhaps repurposing TSDK-263)

2023-05-02 16:48 UTC, mundacho approved these changes

2023-05-02 16:50 UTC, merged