TSDK-568 Group Constructor Minting Transaction
Topl/BramblSc pull request #99
Opened 2023-09-01 22:09 UTC by DiademShoukralla

## Purpose

## Approach

## Testing

## Tickets
*

2023-09-07 15:21 UTC, mundacho requested changes
It looks good to me except for the comment I left. We can make a call and discuss it if you think there is no way around. I saw that some tests require testing for example that the UTXO exist. Maybe another solution is to move this transaction builder entirely to the service kit. What do you think?

2023-09-07 15:21 UTC, mundacho commented on brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
These are very heavy objects to pass around (walletStateApi and bifrostRPC), I would prefer we pass directly whatever is needed instead of computing this here. Also, calling methods from walletState and bifrostRPC adds the possibility of having new different errors. For example, network and database issues. My suggestion is to move (in a new task if necessary) all the code that needs theses two objects to the service-kit

2023-09-07 17:16 UTC, DiademShoukralla commented on brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
As discussed, I will remove the (walletStateApi and bifrostRPC) parameters and replace with whatever is needed directly (TXO, Lock.Predicate). I will also add user validation to ensure proper use of the function

2023-09-08 13:34 UTC, mundacho approved these changes
LGTM

2023-09-08 13:34 UTC, mundacho commented on brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala
> +    assertIO(testTx.map(_.computeId), txFull.computeId)
I think that you do not need the IO anymore if we are not passing the walletState and bifrostQuery

2023-09-08 16:39 UTC, DiademShoukralla commented on brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala
> +    assertIO(testTx.map(_.computeId), txFull.computeId)
You are correct, I have removed those changes

2023-09-08 16:40 UTC, merged